kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: {{ rc.spark-worker.number }}
  selector:
    name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark-worker:1.5.1_v2
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
