kind: Service
apiVersion: v1
metadata:
  name: spark-webui
spec:
  type: {{ svc.spark-webui.balancer }}
  ports:
    - port: {{ svc.spark-webui.port }}
      targetPort: 8080
  selector:
    name: spark-master
